### ISSUE TITLE
✨ Drag and drop to move files between folders

### ISSUE THREAD

**Issue by Greemty** [linagora/twake-drive-legacy#138]
It might be more intuitive to just drag and drop a file to move it.
Section and move it after validation with the modal could be quiet.

Feature: Drag and drop

  Background :
    Given a directory
    Given a User

  Scenario : User move a file in a folder from the same directory
    Given : Actual directory
    When : User hold the click on the file that he wants to move
    Then : File follow the moving cursor
    Then : User move his cursor on the folder in which he wants to move the file
    When : Cursor his over the folder
    Then : Folder highlight
    When : User opt eh file over the folder
    Then : File is move to the folder
    Then : A little info message appear to confirm the action

https://github.com/linagora/TDrive/assets/52284320/af9ea8e5-0172-4a8a-9d18-2b31c4858bdb

**Comment by chibenwa** [comment]
Suggestions to improve this ticket:

 - Gerkin spec detailing the story / expected result
 - Record a video on Google Drive

**Comment by Greemty** [comment]
We might use dnd kit, https://dndkit.com/
