### ISSUE TITLE
Download button doesn't work everywhere

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#155]
where it should work:

- [x] `download` button from the context menu for a file in the `My Drive`
- [x] `download` button from the context menu for a file in the `Shared Drive`
- [x] `download` button from the context menu for a file in the `Shared By Link` view
- [x] `download` button from the context menu for a folder in the `My Drive`
- [x] `download` button from the context menu for a folder in the `Shared Drive`
- [x] `download` button from the context menu for a folder in the `Shared By Link` view
- [x] `download` button in the `More` menu in the "Shared Drive"
- [ ] `download` button in the `More` menu in the "My Drive"
- [ ] `download` button in the `More` menu in the  `Shared By Link` view
- [ ] `download` button in the `Preview Window` 
- [ ] `download` button in the `Preview Window` in the `Shared By Link` view

Where it doesn't work:
- [x] #158
- [x] `download` button from the context menu for a folder in the `Shared Drive`
- [ ] `download` button in the `More` menu in the  `Shared By Link` view
- [ ] `download` button from the context menu for a folder in the `Shared By Link` view

**Comment by Greemty** [comment]
For the last two ones in the *Shared By link*, it seems that the item is undefined which is the cause of the Internal Server Error
