### ISSUE TITLE
Trash: not isolated by user

### ISSUE THREAD

**Issue by chibenwa** [linagora/twake-drive-legacy#178]
**Describe the bug**

User A deletes a file in a private space
User B goes in the trash and sees it

This cause a major breach in user data isolation and is a major security vulnerability.

**Expected behavior**

User B can see the file in the trash ONLY if he has access to the file BEFORE it gets deleted.

**Screenshots**

@guimard trash: 

![Tdrive](https://github.com/linagora/TDrive/assets/6928740/80c0dbda-1a98-4e90-aed6-fc3bb859b95a)

The file "bte-private" was in my local space.

Note that apparently access control works for files in shared space with restricted rights.

**Comment by shepilov** [comment]
Thank you for the bug report, @chibenwa !
yes, we'll need to fix it asap. 
We've created personal space, but trash is still shared

**Comment by shepilov** [comment]
#179 US for separate trash
