### ISSUE TITLE
[Feature] Improve Accessibility

### ISSUE THREAD

**Issue by MontaGhanmy** [linagora/twake-drive-legacy#224]
Work on improving the accessibility of the user interface by adding appropriate ARIA roles, alt text for images, and ensuring keyboard navigation is smooth.

**Comment by VividhPandey003** [comment]
Hey could you please assign me this issue under hacktoberfest. Also wanted to know where can I contact you regarding any doubts I have while contributing

**Comment by MontaGhanmy** [comment]
@VividhPandey003 yes definitely. In case of any doubts feel free to leave a comment here on the issue and I will reach back to you as soon as soon as I see it.
