### ISSUE TITLE
Have an app grid with and on beta.twake.app

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#254]

**Comment by hoangdat** [comment]
hi @guimard , can you describe about the app grid inside the SSO?

**Comment by hoangdat** [comment]
@guimard : 
Problem : LLNG appgrid requires authentication to provide dynamic appgrid (filtered with user rights) but is enable to recognize a Matrix token and is not compatible with a long-time session (using refresh_token). SO I can only put a static JSON file here

**Comment by DianaPotokina** [comment]
Guys @hoangdat @shepilov @guimard why we still don't have app grid ? (not in need window))
