### ISSUE TITLE
Switch off the autocomplete of user for the public platform

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#256]
## User Story
As a user I can only share documents with other users through the "Public link" or if I have the user email. The search autocomplete under "Specific access rules" should be disabled for the public platform.

![Image](https://github.com/linagora/twake-drive/assets/7594703/1fee0279-1a9c-45a7-8418-533ea5dc7ae1)

## Acceptance Criteria
- [ ]  Autocomplete is hidden on the frontend.
- [ ]  The backend only returns the user if the full email is supplied.

**Comment by MontaGhanmy** [comment]
@tprudentova The search option is now disabled on QA, can you please test it?
