### ISSUE TITLE
Quota for the public platform

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#261]

**Comment by tprudentova** [comment]
# Goal of the feature

This feature is necessary to allow users to manage space on their drive and clear it when it’s full. 

# User story

I can see space available on My drive below the list of folders. It is displayed on every tab of Twake Drive. For free accounts quota is 15 GB.

I can see the total space available and space occupied in format “X GB of Y GB used”, as well as a scale that is filled in correspondingly.

![Image](https://github.com/linagora/twake-drive/assets/97684890/d6efbdba-5b51-44af-919c-0ee30ee693a1)

When I occupy 80% of storage, the scale turns yellow.

![Image](https://github.com/linagora/twake-drive/assets/97684890/a2fd1432-61fe-4283-9394-4fb6cd1afab9)

When I occupy 100% of storage, the scale turns red, and a button “Clean up space” appears. 

![Image](https://github.com/linagora/twake-drive/assets/97684890/38af5339-8eb0-4c23-b1bd-9b120e0b21d3)

Clicking this button opens an informational pop-up with text: 

“You’re out of space. You have reached the limit of your storage. Please, delete some files to vacate more space and have access to all features of Twake Drive. 
Our solution is now free for all users, but additional plans are coming soon!”

![Image](https://github.com/linagora/twake-drive/assets/97684890/61e81782-3237-406c-b685-601dd3c7fdbc)

If I occupied 100% of storage and try to upload a file, the file isn’t uploaded, instead I see the same pop-up.

# Acceptance criteria

1. I can see the amount of storage used on every tab of the drive.
2. I can see the total amount of storage available 
3. I can see when I reach 80% of my storage 
4. I can see when I reach limit of my storage. 
5. I cannot upload new files when I reach the limit of my storage.
6. I see some information about how I can free more space.
7. I can close the pop-up with information.

# Mockups

https://www.figma.com/file/qLt94XNHQBvDTmkEmaovBC/Untitled?type=design&node-id=539%3A25627&mode=design&t=EB6MfyhngnBLL3DH-1
