### ISSUE TITLE
Add max upload file size configuraiton

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#262]

**Comment by tprudentova** [comment]
# Goal of the feature

This feature is necessary to avoid situations when a file the user tries to upload is bigger than the storage they have left. 

# User story

When I try to upload a file that is bigger than the storage I have left, the file isn’t uploaded, and I see an informational pop-up with text: 

“A bit too much… :( You don’t have enough storage to upload this file. Please, delete some files to vacate more space or try uploading a smaller one.”

![Image](https://github.com/linagora/twake-drive/assets/97684890/9fb22ea3-54d8-4684-80fe-60f8acb0982b)

# Acceptance criteria

1. I cannot upload a file that is bigger than my remaining storage 
2. I see some information if I try to do so
3. I can close the pop-up with information

# Mockups
https://www.figma.com/file/qLt94XNHQBvDTmkEmaovBC/Untitled?type=design&node-id=540%3A25647&mode=design&t=EB6MfyhngnBLL3DH-1
