### ISSUE TITLE
🇫🇷 French texts issues

### ISSUE THREAD

**Issue by LNGGlago** [linagora/twake-drive-legacy#301]
Various french text issues on v2023.Q3.012 : 

On left menu, its written "Poubelle" instead of "Corbeille"

![image](https://github.com/linagora/twake-drive/assets/151856136/65f97c03-7606-4146-9012-cce821a7f855)

On top bar, in "MyDrive" menu its written "MyDrive" instead of "Mon disque" 

![image](https://github.com/linagora/twake-drive/assets/151856136/474b4354-8667-43bb-b27e-59567d34a77a)

On top bar, in "Shared Drive" menu its written "Shared Drive" instead of "Disque partagé" 

![image](https://github.com/linagora/twake-drive/assets/151856136/3dc9c188-be12-470d-9741-5005a509ec3b)

On top right, on memory usage an "s" must be added to "utilisé"

![image](https://github.com/linagora/twake-drive/assets/151856136/f4b3985a-ed58-4a34-b370-242570d9b2f5)

Having "Rien ici" written is strange in french, it would be better to write "Aucun document." or "Il n'y a rien ici."

![image](https://github.com/linagora/twake-drive/assets/151856136/5545e4d2-8272-4c74-b894-c2480a79a69a)

In the "plus" menu, we don't see the full text. Add a CRLF to the text 

![image](https://github.com/linagora/twake-drive/assets/151856136/dc78567c-ebc7-47ac-a6c5-d740023a8136)

In a folder "..." menu, "Open in a new window" isn't translated. Write "Ouvrir dans une nouvelle fenêtre" instead. (Be careful, the text might be too long for the menu) 

![image](https://github.com/linagora/twake-drive/assets/151856136/aef19436-9479-4f4b-b5f7-71cd31456ce2)

In the "Share menu" : 
 "Lien public d'accès" => "Lien d'accès public"
"Droit d'accès spécifique" => "Droits d'accès spécifiques"
+ What does "Accès Total" means ? How is it different from writing rights ?

In the "rename" tab. Change the button "Changer le nom" => "Renommer"

After pressing "delete" the message isn't really clear. This is more an UX issue I guess, the text should be a confirmation of the deletion with a red button "Supprimer" instead of a blue button "Déplacer vers la corbeille"

**Comment by shepilov** [comment]
@LNGGlago "Accès Total" means full access, that you can also manage permissions for this item

**Comment by shepilov** [comment]
@LNGGlago it is supposed behavior to do not display long lines, I will think about adding tooltips for the long menu items
