### ISSUE TITLE
User names are not displayed when you try to edit permissions 

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#310]
<img width="1431" alt="image" src="https://github.com/linagora/twake-drive/assets/14924963/8cdb4692-f9e7-44a1-9817-f2be02555363">

**Comment by MontaGhanmy** [comment]
@tprudentova can you please test this on QA?

**Comment by tprudentova** [comment]
There are no specific access rules on QA though, so I guess it passed the test :D
