### ISSUE TITLE
[Bug] Expiration date line "blinks" when you type in a password

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#314]
Env: tdrive.qa.lin-saas.com

1. Open Access management of a file 
2. Create a link, enable password and expiration date 
3. Start to type more symbols to the password
4. With each new symbol the expiration date line "blinks"

https://github.com/linagora/twake-drive/assets/97684890/4230b4dd-220b-4198-ac86-ccd013d2a374

**Comment by MontaGhanmy** [comment]
@tprudentova can you please test this on QA?

**Comment by tprudentova** [comment]
Looks good!

**Comment by shepilov** [comment]
@tprudentova could you please close issue if everything is fine?
