### ISSUE TITLE
[Bug] When you follow a file link, the window for entering password is shown for a second 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#315]
Env: tdrive.qa.lin-saas.com

1. Open Access management of a file 
2. Create a link not protected by a password
3. Follow that link 
4. A window for entering password is still shown for a second before the file is opened

https://github.com/linagora/twake-drive/assets/97684890/3cb43c01-da4d-4608-8991-10ef01f8c064

**Comment by ericlinagora** [comment]
possibly related to #512
