### ISSUE TITLE
Problems with path breadcrums in "Shared with me" section

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#318]
In the "Shared with me" section in the path to the file, there is no root folder. The "root" folder for this file is the folder that was shared. But the context menu that we have for the first folder is still showing items "My Drive" and "Shared Drive"

**To Reproduce**
1. Go to the 'Shared with me section'
2. Go to one. step deeper in the folder tree
3. Click on 'Context menu' in the breadcrumbs

**Expected behavior**
Remove the context menu, and go directly to this folder

**Screenshots**

**Comment by Facyla** [comment]
Alternate behaviour : keep the list, but add all parent folders in the list.
