### ISSUE TITLE
[Bug] Navigation into the folders tree

### ISSUE THREAD

**Issue by Facyla** [linagora/twake-drive-legacy#361]
**Describe the bug**
The navigation in the folders tree seems to have a few issues related to navigation in the folder's tree, see attached screen capture for behaviour : 
- no breadcrumb or direct link to the closest parent
- link click behaviour seems inconsistent : sometimes clicking once opens the folder, sometimes it requires clicking 2 times
- clicking on breadcrumb link brings whether to root folder or to 2 level parent folder
- clicking from the root folder brings wheter to the folder, or to a contained subfolder, depending on previous navigation

**To Reproduce**
Tested with my account on web version of TDrive : https://tdrive.linagora.com/
1.Navigation into the following structure : 
- Shared folders :
    - CEREMA_2023... :
        - Notes-Ateliers :
            - (file1)
            - (file2)

2. Click on "CEREMA...", then on "Notes-Ateliers" => the files are displayed. Clicking again on "Notes-Ateliers" in the breadcrumb has no action (which is OK)
3. Click on "Partagé avec moi" (Shared with me) => brings to the Shared folders  (which is OK but one would appreciate to be able to go 1 level, related to #326 )
4. Click again on "CEREMA..." => brings to the "Notes-Ateliers" subfolder instead of into the clicked folder
5. Click on "Notes-Ateliers" => brings back 1 level (into "CEREMA...") => inconsistent with (2)
6. Other reported behaviours : 

**Expected behavior**
Consistent navigation : each link should produce the same result in all situations (= navigate to the same target). 

**Screenshots**
[Capture vidéo du 2024-02-09 10-41-27.webm](https://github.com/linagora/twake-drive/assets/286492/bdf657d9-b080-4d15-bb14-ddee609e3f3f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser: Firefox
 - Version: Mozilla Firefox snap for Ubuntu, version 122.0 (64 bits)

**Comment by shepilov** [comment]
thank you @Facyla , we'll try to fix it asap
