### ISSUE TITLE
[Improvement] Remove the "Account parameters" heading

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#388]
Right now we have the phrase "Account parameters" twice right next to each other

<img width="1206" alt="Screenshot 2024-02-27 at 18 09 26" src="https://github.com/linagora/twake-drive/assets/97684890/3cf2a03e-58f4-409a-9de6-1aa344b4f70f">

**Comment by shepilov** [comment]
@tprudentova , yes, it should've been the menu to the left, and the title to the right.
And probably it will be menu when we will have more than one point
