### ISSUE TITLE
SSO Logout doesn't work 

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#39]
https://auth.tdrive.qa.lin-saas.com/oauth2/logout?post_logout_redirect_uri=https%3A%2F%2Ftdrive.qa.lin-saas.com%2Fsignout#

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/14924963/237051266-037e52d7-1452-4e84-8764-2472c2fcba66.png">

**Comment by MontaGhanmy** [comment]
Issue was with LemonLDAP config "oidcRPMetaDataOptionsPostLogoutRedirectUris" field.
