### ISSUE TITLE
[Bug] Cannot download a folder

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#404]
MocOS, Safari 

1. Open Twake Drive 
2. Try to download a folder with contents 
3. Infinite loading 

NB: I can download an empty folder though

https://github.com/linagora/twake-drive/assets/97684890/42cfd772-cef7-4137-afd7-489151433a75

**Comment by shepilov** [comment]
@tprudentova could you give more details about this specific folder? 
It looks for another one it works
