### ISSUE TITLE
Small UI issues

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#43]
Add coming soon to the setting in the TDrive

- [x] The dark theme button is the create menu
<img width="389" alt="image" src="https://github.com/linagora/TDrive/assets/14924963/68b46b5f-14fd-455d-8401-635dfbade93d">

- [x] Fix icons in the search menu
<img width="578" alt="image" src="https://github.com/linagora/TDrive/assets/14924963/3d7c0d8a-3161-4340-a527-a04764f8eaad">

-[ ] Add coming soon to the setting in the TDrive and remove link to the console

**Comment by RomaricMourgues** [comment]
Fixed in #49
