### ISSUE TITLE
[Bug] The user can't go the the internal folder if the folder was shared with him by link

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#432]
- Create folder "ABC" in your personal drive
- Got to the folder "ABC"
- Crete folder "DEF" inside
- Share folder "ABC" by a link with "write" permission
- Go by that link in the clean session
- Click on the "DEF" folder
- Nothing is happening, nothing in the "console" and "network" tabs in the browser

<img width="1437" alt="image" src="https://github.com/linagora/twake-drive/assets/14924963/04d2ef6f-0906-4bd8-a7d9-9b3be095e6f3">

**Comment by tprudentova** [comment]
https://github.com/linagora/twake-drive/assets/97684890/243dd41d-4495-44dc-810f-e8d9329dfda9
