### ISSUE TITLE
[Feature] Make possible to run CLI application for Twake Drive

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#438]
- [x]  Try to run the existing application that we have
- [x]  Make it possible to run `tdrive/backend/node/src/cli/cmds/search_cmds/index_all.ts` to rebuild search index
- [x]  Update documentation, on how to build and run cli scripts
- [ ]  (OPTIONAL) Modify this rebuild process to make it possible to delete entries from the search index that had been deleted from the DB

**Comment by ericlinagora** [comment]
Didn't find a good way to do the optional task: it would require a sorted complete scan of both data sources to match up superfluous entries
