### ISSUE TITLE
[Improvement] Right now it's nearly impossible to set expiration date manually 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#468]
1. Open access management 
2. Enable expiration date 
3. Try typing it in with your keyboard 
4. The field blinks and disables after each entered number 

I suggest we either disable the ability to type in expiration date manually (not recommended :D) or fix it 

https://github.com/linagora/twake-drive/assets/97684890/4b50181a-3601-4c30-b1e5-3dd29fdd40b5

**Comment by shepilov** [comment]
fixed in #50
