### ISSUE TITLE
Files downloaded as 'Untitled'

### ISSUE THREAD

**Issue by guimard** [linagora/twake-drive-legacy#469]
**Describe the bug**

A file is shared with me (pure ASCII name). I want to download it, it is stored as Untitled-20240320-0827.docx

**To Reproduce**

Don't know how to reproduce, this is the first time is see that _(our internal Tdrive)_

**Expected behavior**

Don't change the name

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox

**Comment by tprudentova** [comment]
I've got a similar bug when trying to save a file with its name in Russian, could be related 


https://github.com/linagora/twake-drive/assets/97684890/931ac2c5-ba2b-469c-b4a8-9666953cb0ff
