### ISSUE TITLE
[Improvement] Files to be sorted chronologically 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#497]
Current behaviour: files are sorted in alphabetical order 
Desired behaviour: files are sorted in chronological order

**Comment by shepilov** [comment]
@tprudentova we need a user story and design to change this UX, to change the sort order etc ...

**Comment by tprudentova** [comment]
# Goal of the feature 

As a user, I want to view files in chronological order 

# User story

Items in all parts of the drive are sorted by time of last modification (newest to oldest). 

I first see all the folders sorted chronologically, then all the files sorted chronologically. 

The actions considered as modifications are:

- Editing with OnlyOffice
- Renaming
- Adding files to a folder

If no modifications have ever been made to a file/folder, the last modification date/time is the date/time of the upload.

<img width="1280" alt="Screenshot 2024-05-14 at 11 26 49" src="https://github.com/linagora/twake-drive/assets/97684890/bbf9284b-89c3-48c7-a335-c9513473b293">

# Acceptance criteria 

1. My files are sorted by last modification date in all parts of the drive 
2. The sorting order is descending (newest at the top)
3. I first see all the folders sorted chronologically, then all the files sorted chronologically
