### ISSUE TITLE
Files in Shared with me take too long to load

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#499]
https://github.com/linagora/twake-drive/assets/97684890/a0adea73-93e2-46f7-8f96-1336b60b2495

**Comment by shepilov** [comment]
It's connected with permissions, and it's not only about "Shared with you" but for all folders >200 files

For this, I think we have a user story about paging in the search results and changing the layout of the files browser as well

Having filters and ability to sort files
