### ISSUE TITLE
User picker does not work well

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/twake-drive-legacy#50]
**Describe the bug**
- [ ] The user picker in access management doesn't work very well and doesn't match the current UI. We should rebuild it from scratch.
- [ ] Also the users are not loaded until we open the picker
- [x] Also we will need to remove the anonymous user from user search

**To Reproduce**
Open account B and lookup a file access management created by user A, you will not see user A:

Before searching:
![Screenshot 2023-05-11 at 10 58 02](https://github.com/linagora/TDrive/assets/14353924/878e74ce-8cf9-4139-974d-2b6de3d25914)

After searching (user repository updated): 
![Screenshot 2023-05-11 at 10 58 07](https://github.com/linagora/TDrive/assets/14353924/27dae038-2cee-4462-8586-e8a2e0eb32d2)

**Comment by ericlinagora** [comment]
Did some UI work on this. Search issues for me were related to elastic vs open search. The behaviour when adding a user isn't super clear to me, eg if a user has rights then is added with "no rights" in the drop down

**Comment by shepilov** [comment]
@ericlinagora he can have right to the parent directory, but do not to the child one, 
and if he has right to the parent directory it's do not displays in the list, that's why it's not clear for the user

**Comment by ericlinagora** [comment]
Not sure I understand then, will need someone to show me

**Comment by shepilov** [comment]
The new design for access management modal window https://www.figma.com/file/CWz4DatnJ7Qhl3JycJhbFY/TDrive---MUI3?type=design&node-id=1199-41375&mode=design&t=W8oEfqYP13t46wOD-0

**Comment by ericlinagora** [comment]
https://www.figma.com/proto/CWz4DatnJ7Qhl3JycJhbFY/TDrive---MUI3?type=design&node-id=1585-1262&t=8xKOrMMDLhbkdmA5-0&scaling=min-zoom&page-id=1583%3A102&starting-point-node-id=1585%3A1262&hide-ui=1
