### ISSUE TITLE
[Improvement] Add some sort of highlight in the breadcrumps for the part of the drive I'm currently in

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#505]
Like, make it blue.... Or underlined 
<img width="1278" alt="Screenshot 2024-04-28 at 19 30 56" src="https://github.com/linagora/twake-drive/assets/97684890/92ece6be-1525-44d4-9c40-4f06ef3fc241">

**Comment by shepilov** [comment]
@Bobpodvalnyi could you please advice how we can highlight it
