### ISSUE TITLE
Implement OIDC back-channel-logout

### ISSUE THREAD

**Issue by guimard** [linagora/twake-drive-legacy#509]
As describe in [TWP linagora/twake-workplace-private#99](https://github.com/linagora/twake-workplace-private/issues/99), we want to have logout. The only unbuggy way to do it is to use OIDC [Back Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) like Twake-Mail and Twake-Chat.

Please implement it _(with [backchannel_logout_session_required](https://openid.net/specs/openid-connect-backchannel-1_0.html#BCRegistration), to avoid deleting all sessions)_.

**Comment by shepilov** [comment]
<img width="769" alt="image" src="https://github.com/linagora/twake-drive/assets/14924963/84d121e7-4580-4ad1-8223-ce9dcac01c32">

- [ ] Implements session storage with sub/sid 
- [ ] Add sid to the Twake Drive access token
- [ ] Validate sid on every Twake Drive request
- [ ] Implement backchannel logout URI with logout token validation

**Comment by shepilov** [comment]
@guimard logout URL should be with POST like this?

/backchannel_logout HTTP/1.1
  Host: rp.example.org
  Content-Type: application/x-www-form-urlencoded
logout_token=eyJhbGci...

**Comment by guimard** [comment]
> @guimard logout URL should be with POST like this?
> 
> /backchannel_logout HTTP/1.1 Host: rp.example.org Content-Type: application/x-www-form-urlencoded logout_token=eyJhbGci...

Yes this is exactly what OP does

**Comment by guimard** [comment]
Hi @shepilov, could you give me the URL to set in LLNG conf ?

**Comment by shepilov** [comment]
@guimard https://drive.stg.lin-saas.com/internal/services/console/v1/backchannel_logout
I've just deployed it on the staging

**Comment by guimard** [comment]
Configuration updated, let's test. Note that it may fail until @rezk2ll study the new flow
