### ISSUE TITLE
Remove trailing slash when reading configuration in the OnlyOffice connector

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#515]
It's also a big mystery we should put the URL with or without a trailing slash in the URL confirmation for the connector.

So it's better to remove all slashes from the configuration and internally use URLs starting from slash

**Comment by ericlinagora** [comment]
Most places I found remove any extraneous slashes before concatenating them, however the investigation revealed a series of other problems with the integration. I have not found a place where this was an issue, so marking as won't fix until more specific instructions for reproduction of the issue are added.
