### ISSUE TITLE
[Bug] File downloaded through selection has a weird name

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#596]
1.0.3, tested on Safari, Firefox, Opera; https://drive.stg.lin-saas.com/

1. Select a file 
2. Click Download selected items 
3. The name of the file is really weird 

Expectation: it has the same name as on the drive 

https://github.com/user-attachments/assets/f05ce41c-d877-41a5-890f-cebb72a72ee4

**Comment by ericlinagora** [comment]
We tried to reproduce this one, but couldn't. Even with cyrillic characters. Can you reproduce with a newly uploaded file in the current staging ? If so can we have a copy of that file please ?
