### ISSUE TITLE
[Improvement] Shouldn't be able to move files from folder A to folder A

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#611]
1.0.3, tested on Safari, Firefox, Opera; https://drive.stg.lin-saas.com/

1. Open context menu of a file in Folder A
2. Select Move
3. I can move to the very same folder (logically nothing actually changes)

Expectation: Button Move in the dialogue window is inactive when I'm in the folder where the file is located

https://github.com/user-attachments/assets/e6728338-55ac-4b3a-b373-61c7c1e6bc83

**Comment by shepilov** [comment]
@tprudentova you should go to the folder we you want to move files, and not just select it
