### ISSUE TITLE
[BUG] Can't find some users

### ISSUE THREAD

**Issue by Te-Z** [linagora/twake-drive-legacy#616]
**Describe the bug**

When I try to give access to a file, I can't find some users with partial or full email address

Tested on Chrome https://drive.stg.lin-saas.com/

![image](https://github.com/user-attachments/assets/d8a6d60f-776d-4b64-9384-a2b344391f4d)

**Comment by shepilov** [comment]
@Te-Z "manage acceess" feature should be disabled for SaaS service for now, see #584, so that you can't find any user it's normal, but we should remove the whole pint in the context menu for "access management"
