### ISSUE TITLE
[Improvement][UI][Web Mobile] Date of last modification information is not aligned between items

### ISSUE THREAD

**Issue by dab246** [linagora/twake-drive-legacy#655]
### Env: 

- Version: `1.0.4`
- Server: `stg.lin-saas.com`
- Platform: `Microsoft Edge (Mobile - iPhone)`

### Steps to reproduce

1. Open Twake Drive 
2. See some files and folders there 

## Expectation

- Left align all items

## Evidence

![IMG_8815](https://github.com/user-attachments/assets/1a2dd7e0-d427-4e20-8360-de0852268619)

**Comment by ericlinagora** [comment]
This occurs when the size field is larger than some threshold, fix is not trivial
