### ISSUE TITLE
[Improvement][UI] Add left padding to `access right` button

### ISSUE THREAD

**Issue by dab246** [linagora/twake-drive-legacy#657]
### Env: 

- Version: `1.0.4`
- Server: `stg.lin-saas.com`
- Platform: `Chrome & Microsoft Edge`

### Steps to reproduce

1. Click “…” next to a folder or a file on my drive
2. Select Share

## Expectation

- Always align all values ​​of `Access right` to both sides. 
- Support multiple language

## Evidence

<img width="1440" alt="Screenshot 2024-09-24 at 18 32 01" src="https://github.com/user-attachments/assets/800bf5bb-0d66-45c7-b16d-0bbbc97858a3">

**Comment by ericlinagora** [comment]
NB: in chrome in dark mode the dropdown list is white on white
