### ISSUE TITLE
[BUG] Error message `Unable to load your files.` appears when performing `Rename` of a file shared with `Write` access right

### ISSUE THREAD

**Issue by dab246** [linagora/twake-drive-legacy#658]
### Env: 

- Version: `1.0.4`
- Server: `stg.lin-saas.com`
- Platform: `Chrome & Microsoft Edge`

### Steps to reproduce

1. I receive the file link
2. I click on that link
3. A web page with the file is opened
4. On the page, I perform select `Rename`
5. Enter name file to input field.
6. Click `Update name` button

## Expectation

- Remove error message `Unable to load your files.` when name update is successful.

## Evidence

https://github.com/user-attachments/assets/fe878f90-6780-45f6-b411-b286f8a5236a

**Comment by shepilov** [comment]
duplicate for #639
