### ISSUE TITLE
[Bug] Clicking Exit trash doesn't do anything

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#663]
1.0.4, drive.stg.lin-saas.com, tested on Safari, Opera, MacOS

1. Open Trash
2. Click More 
3. Click Exit trash 
4. Nothing happens 

If this is a bug and something is meant to happen, we need to fix this; if it's absence of the feature, we need to remove this button 

https://github.com/user-attachments/assets/a3143532-82df-4d5d-bd01-aeceb1bac1d2

**Comment by ericlinagora** [comment]
Fixed in 1a43a75479af0a23655755c97971ede7aa401a40
