### ISSUE TITLE
[Bug] If a file is named in Russian, it's downloaded with a weird name

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#665]
1.0.4, drive.stg.lin-saas.com, tested on Safari, Opera, MacOS

1. Upload a file with a Russian name 
2. Download it
3. It has a really weird name

https://github.com/user-attachments/assets/90a2b32b-def3-46d1-bf9e-098e7675cfd2

**Comment by ericlinagora** [comment]
I couldn't reproduce, I tried opera and FF on linux, and FF on mac os. (my version of safari can't load drive because of the new regexp group syntax used). Maybe @tprudentova can you paste the specific file name you tested please ?
