### ISSUE TITLE
[Bug] Irrelevant warning when renaming a file shared with me by link

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#667]
1.0.4, drive.stg.lin-saas.com, tested on Safari, Opera, MacOS

1. Share a file by link with Write permissions 
2. Follow that link 
3. Rename a file 
4. A warning "Unable to load your files" appears. The file is renamed though

https://github.com/user-attachments/assets/e75ea526-963e-43b2-880b-b75905956fe9

**Comment by tprudentova** [comment]
Same when deleting a file while having full access 

https://github.com/user-attachments/assets/d6b2437d-895a-4e74-af25-5424e0661cbb

**Comment by ericlinagora** [comment]
Related: #638 and #639 
These should probably be considered separate and this issue shouldn't mix them up

**Comment by ericlinagora** [comment]
> Same when deleting a file while having full access
> Screen.Recording.2024-09-25.at.16.30.36.mov

Why is it "Mon disque" but everything else in english ? which language do you have set @tprudentova ?

**Comment by tprudentova** [comment]
> > Same when deleting a file while having full access
> > Screen.Recording.2024-09-25.at.16.30.36.mov
> 
> Why is it "Mon disque" but everything else in english ? which language do you have set @tprudentova ?

It's English. Reported in #436
