### ISSUE TITLE
[Bug] [PRODUCTION] No previews for docx files

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#694]
drive.twake.app, 1.0.4, tested on Safari, Firefox 

1. Upload a docx file 
2. Try opening its preview 
3. Error "Tdrive frontend is not here, please do one of the following..."

Expectation: I see the preview 

https://github.com/user-attachments/assets/b98b064f-7210-4420-b114-c0d764d96f2b

**Comment by ericlinagora** [comment]
Seems fixed by a redeploy of the connector at Today ⁨4:36 PM⁩ 1729521390586
