### ISSUE TITLE
[Bug] Messed up sorting by size if there are empty folders 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#704]
drive.stg.lin-saas.com, 1.0.5, tested on Safari, Firefox, Opera

1. Create a few folders, some of which are empty 
2. Sort by size 
3. The sorting is wrong (for instance, if it's descending, the empty folders are at the top, the rest are sorted properly)

<img width="1280" alt="Screenshot 2024-10-23 at 17 27 13" src="https://github.com/user-attachments/assets/2e36a805-9e6f-401e-ba6f-8213dbe0c1d4">
<img width="1280" alt="Screenshot 2024-10-23 at 17 27 27" src="https://github.com/user-attachments/assets/31fd854c-2e67-4db9-93c9-da00f7824581">

**Comment by shepilov** [comment]
@tprudentova it's only for the new folders? after a page refresh everything is fine?

**Comment by tprudentova** [comment]
@shepilov nope, all empty folders, even old ones
