### ISSUE TITLE
[Bug] Search box isn't cleared after the search window is closed

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#705]
drive.stg.lin-saas.com, 1.0.5, tested on Safari, Firefox, Opera

1. Open Search 
2. Search something 
3. Don't clear the search field manually 
4. Close the search window 
5. The search requests is still displayed in the search field 

Expectation: the search field is cleared after I close the search window

https://github.com/user-attachments/assets/db806ec6-39dd-41e0-812f-98dedac1f2d7

**Comment by shepilov** [comment]
@tprudentova It's a feature and not a bug
Probably it's a bug that it can't be cleared when the modal window is closed. And also that the modal window is not connected to this input

**Comment by ericlinagora** [comment]
Maybe just add a right aligned X button to clear the field ? would that be enough ?
