### ISSUE TITLE
[Bug] Access rights error when opening a docx file preview

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#741]
vv1.0.5rc6, drive.stg.lin-saas.com, tested on Safari, Firefox 

1. Upload a docx file 
2. Try opening its preview 
3. Access rights error 

https://github.com/user-attachments/assets/5c0963a0-bfa3-4b3a-b3ce-b1fbc8d5ec39

**Comment by ericlinagora** [comment]
This was an issue with the environment's only office deployment, since solved.
