### ISSUE TITLE
Redesign account menu

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#744]
https://www.figma.com/design/CWz4DatnJ7Qhl3JycJhbFY/TDrive---MUI3?node-id=2566-175&node-type=frame&t=1QqNSEeubhw4O2hc-0

<img width="619" alt="image" src="https://github.com/user-attachments/assets/2b769399-4bca-492a-8fe8-3aea2ae9440b">

Change icon and margins according to design

Make it possible to select an email

**Comment by lethemanh** [comment]
> Make it possible to select an email

@shepilov is there any action when user select email?

**Comment by shepilov** [comment]
> > Make it possible to select an email
> 
> @shepilov is there any action when user select email?

nope, just to copy it with ctrl+c if needed
