### ISSUE TITLE
[Bug] Not allow choose the location for downloaded file/folder in Opera browser

### ISSUE THREAD

**Issue by thuyenh1081** [linagora/twake-drive-legacy#749]
vv1.0.5rc6, drive.stg.lin-saas.com, Opera

Steps:
1. Click ... beside a file/folder
2. Choose download
>>> see that the file/folder is downloaded immediately, without allow choosing location for loading and set name for download file also
Expect: Allow us choosing location for downloaded file and set name for it also ( Refer Chrome for correct behavior) 
Please refer the attached video for bug : 
https://github.com/user-attachments/assets/c653f2f9-70ad-4c90-b4d1-72d5a0e07900

**Comment by shepilov** [comment]
@thuyenh1081 is it a feature request?
it's not possible in the browser for security reasons.

**Comment by thuyenh1081** [comment]
@shepilov  I think that is existing feature because we already have test case for it and this issue is not happend in some browsers like Chrome, Edge ( video for correct behavior in Chrome: 
https://github.com/user-attachments/assets/e6adffc3-be68-438c-ae39-c396c5074b5c

Link for test case: https://www.notion.so/linagora/DRIVE-Release-1-0-5-14362718bad18079addaf2effce34e7c?p=14362718bad1819bb5cad4f7b70d92a4&pm=s

**Comment by thuyenh1081** [comment]
@shepilov I have just know that the showing of download location popup is belong Browser. I have changed setting of browser to show the popup and could see the location popup is shown, I could choose location for downloading. Yes, this bug need to be closed :)
