### ISSUE TITLE
[Bug] OnlyOffice changes aren't applied

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#754]
drive.stg.lin-saas.com, v1.0.5-rc11, tested on Safari, Firefox

1. Create a docx document 
2. Open it
3. Click Edit with OnlyOffice 
4. Make some changement 
5. Close the preview and open it again 
6. The changes aren't applied. If you click Edit with OnlyOffice again, you see an error 

https://github.com/user-attachments/assets/57221bba-11ee-4d84-8071-4e541fab0651

**Comment by ericlinagora** [comment]
After conversation with @tprudentova , there is an unavoidable time delay before the file is updated in drive by the only office server. The resolution to avoid scaring users will be something about the UI, either showing the preview as an actual readonly editor in the same key, display current editing session keys on drive items as "currently edited drive item", show an overlay on the preview screen in that case notifying that the visible version is not the latest, more aggressively storing on force save events - create versions ?
